# Generated by Django 4.2.6 on 2023-10-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_member_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
    ]
